### ISSUE TITLE
Interpolating `QuadratureWeight` gives TSFC error

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/tsfc#208] opened 2020-04-24 13:18 UTC
I want to evaluate some expressions at quadrature points. I try:

```
from firedrake import *
from ufl.geometry import QuadratureWeight

mesh = UnitIntervalMesh(2)

Qse = FiniteElement("Quadrature", mesh.ufl_cell(), degree=2, quad_scheme="default")
Qs = FunctionSpace(mesh, Qse)

# Works
x = SpatialCoordinate(mesh)[0]
xq = interpolate(x, Qs)
print(xq.dat.data_ro)

# Fails
w = QuadratureWeight(mesh)
wq = interpolate(w, Qs)
print(wq.dat.data_ro)
```

The interpolation of x works, but the interpolation of the quadrature weight doesn't. It yields

```
Traceback (most recent call last):
  File "bug.py", line 16, in <module>
    wq = interpolate(w, Qs)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/interpolation.py", line 36, in interpolate
    return Interpolator(expr, V, subset=subset, access=access).interpolate()
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/interpolation.py", line 58, in __init__
    self.callable, arguments = make_interpolator(expr, V, subset, access)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/interpolation.py", line 163, in make_interpolator
    loops.extend(_interpolator(V, tensor, expr, subset, arguments, access))
  File "</mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/lib/python3.6/site-packages/decorator.py:decorator-gen-22>", line 2, in _interpolator
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/utils.py", line 64, in wrapper
    return f(*args, **kwargs)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/firedrake/firedrake/interpolation.py", line 205, in _interpolator
    ast, oriented, needs_cell_sizes, coefficients, _ = compile_expression_dual_evaluation(expr, to_element, coords, coffee=False)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/tsfc/driver.py", line 364, in compile_expression_dual_evaluation
    expr, = fem.compile_ufl(expression, **config, point_sum=False)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/tsfc/fem.py", line 645, in compile_ufl
    result = map_expr_dags(context.translator, expressions)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/ufl/ufl/corealg/map_dag.py", line 73, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/tsfc/ufl_utils.py", line 145, in _modified_terminal
    return self.modified_terminal(o)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/tsfc/fem.py", line 303, in modified_terminal
    return translate(mt.terminal, mt, self.context)
  File "/usr/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/tsfc/fem.py", line 320, in translate_quadratureweight
    return ctx.weight_expr
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/gem/utils.py", line 19, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/tsfc/fem.py", line 222, in weight_expr
    return self.quadrature_rule.weight_expression
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/gem/utils.py", line 19, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/mnt/ntfs/data/install-scripts/firedrake/firedrake-dev-20200222-mpich/src/tsfc/tsfc/fem.py", line 206, in quadrature_rule
    return make_quadrature(integration_cell, self.quadrature_degree)
AttributeError: 'PointSetContext' object has no attribute 'quadrature_degree'
```

**Comment by wence-** [comment] 2020-04-24 13:45
There is no quadrature here, how are we to deduce what the quadrature weight is?

**Comment by pefarrell** [comment] 2020-04-24 20:53
Qs has to have a quadrature scheme; that's the one that should be used.

**Comment by wence-** [comment] 2020-04-30 15:41
And fixed.

**Comment by ReubenHill** [comment] 2021-08-24 09:59
It seems this got broken again when I merged #247 because `runtime_quadrature_rule` is incorrectly set to `true` in the second case:

https://github.com/firedrakeproject/tsfc/blob/b7c66f1ee58637a254ec634ac1d1e369a8c7c41a/tsfc/driver.py#L370-L377

I've made a hotfix PR #259 .

Note that #250 also fixes this.

**Comment by ReubenHill** [comment] 2021-08-24 09:59
I'm going to add this as a test to firedrake to avoid this regression happening again

**Comment by ReubenHill** [comment] 2021-08-24 10:26
Test added in https://github.com/firedrakeproject/firedrake/pull/2195

**Comment by wence-** [comment] 2022-02-25 18:12
Fixed.

**Closed by wence-** 2022-02-25 18:12 UTC
